# -*- coding: utf-8 -*-
"""disunity_apply.py -- IDA idalib script

Reads unity_meta.json produced by `disunity meta`, applies:
  1. All struct types (IL2CPP class layouts) via parse_decls
  2. Function creation + renaming
  3. Function signatures with typed this pointers referencing structs
  4. EOL comments (BL annotations, field accesses)
  5. Hex-Rays decompilation of focus functions

Usage:
  python3 disunity_apply.py <libil2cpp.so> <unity_meta.json> [<output_dir>]

Requires:
  - IDA Pro with idalib (idapro Python package)
  - Hex-Rays decompiler for ARM64 (for decompilation phase)
"""

import json
import os
import sys
import time


def log(msg):
    sys.stderr.write(msg + "\n")
    sys.stderr.flush()


def sanitize(name):
    """Sanitize a name for use as C identifier."""
    out = []
    for ch in name:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    s = "".join(out)
    if s and s[0].isdigit():
        s = "_" + s
    return s[:120] if len(s) > 120 else s


def sanitize_filename(name):
    """Sanitize for filenames (allows dots and hyphens)."""
    out = []
    for ch in name:
        if ch.isalnum() or ch in ("_", "-", "."):
            out.append(ch)
        else:
            out.append("_")
    s = "".join(out)
    return s[:120] if len(s) > 120 else s


def resolve_meta_path(argv):
    """Resolve unity_meta.json path from argv or relative to this script."""
    if len(argv) >= 3 and argv[2]:
        return argv[2]
    script_dir = os.path.dirname(os.path.abspath(__file__))
    candidate = os.path.join(script_dir, "..", "unity_meta.json")
    if os.path.exists(candidate):
        return candidate
    return None


def apply_metadata(meta, idc, ida_funcs, ida_typeinf, ida_auto=None):
    """Apply disunity metadata to an open IDA database (phases 1-4).

    Importable by ida-headless-mcp's import_il2cpp tool.

    Args:
        meta: parsed unity_meta.json dict
        idc: IDA idc module
        ida_funcs: IDA ida_funcs module
        ida_typeinf: IDA ida_typeinf module
        ida_auto: IDA ida_auto module (optional, for re-analysis)

    Returns:
        dict with stats: functions_created, functions_named, structs_created,
        signatures_applied, comments_set
    """
    pointer_size = meta.get("pointer_size", 8)
    log("  pointer_size: %d" % pointer_size)

    stats = {
        "functions_created": 0,
        "functions_named": 0,
        "structs_created": 0,
        "signatures_applied": 0,
        "comments_set": 0,
    }

    # ================================================================
    # Phase 1: Generate C header and parse all types at once
    # ================================================================
    classes = meta.get("classes", [])
    struct_names = {}  # class_name -> C struct name

    header_lines = []
    header_lines.append("// Auto-generated by disunity for IDA")
    header_lines.append("")

    for cls in classes:
        cname = cls.get("class_name", "")
        if not cname:
            continue
        ns = cls.get("namespace", "")
        sname = "IL2CPP_" + sanitize(cname)
        if ns:
            sname = "IL2CPP_" + sanitize(ns) + "_" + sanitize(cname)
        size = cls.get("instance_size", 0)
        fields = cls.get("fields", [])
        if size > 0 and fields:
            header_lines.append(build_class_struct(sname, size, fields, pointer_size))
            header_lines.append("")
            struct_names[cname] = sname
            if ns:
                struct_names[ns + "." + cname] = sname

    header = "\n".join(header_lines)

    if header.strip():
        nerr = ida_typeinf.idc_parse_types(header, 0)
        stats["structs_created"] = len(struct_names)
        if nerr == 0:
            log("Phase 1: parsed %d struct types (0 errors)" % stats["structs_created"])
        else:
            log("Phase 1: WARN: %d parse errors" % nerr)
    else:
        log("Phase 1: skipped (no types)")

    # ================================================================
    # Phase 2: Create/rename functions
    # ================================================================
    functions = meta.get("functions", [])
    log("Phase 2: creating/renaming %d functions..." % len(functions))
    for entry in functions:
        addr = int(entry["addr"], 16)
        name = sanitize(entry["name"])
        size = entry.get("size", 0)

        fn = ida_funcs.get_func(addr)
        if fn is None:
            end = addr + size if size > 0 else addr
            if ida_funcs.add_func(addr, end):
                stats["functions_created"] += 1
            else:
                idc.create_insn(addr)
                if ida_funcs.add_func(addr, end):
                    stats["functions_created"] += 1

        flags = idc.SN_NOWARN | idc.SN_NOCHECK
        if not idc.set_name(addr, name, flags):
            fallback = "%s_%x" % (name, addr)
            idc.set_name(addr, fallback, flags)
        stats["functions_named"] += 1

    log("  created=%d named=%d" % (stats["functions_created"], stats["functions_named"]))

    if ida_auto:
        log("  re-analyzing...")
        ida_auto.auto_wait()

    # ================================================================
    # Phase 3: Apply function signatures
    # ================================================================
    log("Phase 3: applying function signatures...")
    sig_failed = 0
    for entry in functions:
        addr = int(entry["addr"], 16)
        owner = entry.get("owner", "")
        pc = entry.get("param_count", 0)
        name = entry["name"]
        ret = entry.get("return_type", "void*")
        is_static = entry.get("is_static", False)

        proto = build_function_prototype(name, owner, pc, ret, is_static, struct_names)
        if not proto:
            continue

        try:
            decl = idc.parse_decl(proto, 0)
            if decl and idc.apply_type(addr, decl, 1) != False:
                stats["signatures_applied"] += 1
            else:
                sig_failed += 1
        except Exception:
            sig_failed += 1

    log("  applied=%d failed=%d" % (stats["signatures_applied"], sig_failed))

    # ================================================================
    # Phase 4: Set comments
    # ================================================================
    comments = meta.get("comments", [])
    log("Phase 4: setting %d comments..." % len(comments))
    for entry in comments:
        addr = int(entry["addr"], 16)
        text = entry["text"]
        try:
            idc.set_cmt(addr, text, 1)
            stats["comments_set"] += 1
        except Exception:
            pass
    log("  set=%d" % stats["comments_set"])

    return stats


def main():
    if len(sys.argv) < 2:
        log("Usage: python3 disunity_apply.py <libil2cpp.so> [<unity_meta.json>] [<output_dir>]")
        sys.exit(1)

    binary_path = sys.argv[1]
    meta_path = resolve_meta_path(sys.argv)
    out_dir = sys.argv[3] if len(sys.argv) > 3 else None

    if not os.path.exists(binary_path):
        log("ERROR: binary not found: %s" % binary_path)
        sys.exit(1)
    if meta_path is None or not os.path.exists(meta_path):
        log("ERROR: unity_meta.json not found. Pass as argument or place script in <output>/ida/")
        sys.exit(1)

    log("disunity_apply (IDA): loading %s" % meta_path)
    with open(meta_path, "r") as f:
        meta = json.load(f)

    # ---- Open database ----
    log("Opening binary in IDA: %s" % binary_path)
    import idapro
    idapro.enable_console_messages(False)

    result = idapro.open_database(binary_path, True)
    if result != 0:
        for ext in (".i64", ".idb", ".id0", ".id1", ".id2", ".nam", ".til"):
            p = binary_path + ext
            if os.path.exists(p):
                os.remove(p)
        result = idapro.open_database(binary_path, True)
        if result != 0:
            log("ERROR: failed to open database (code %d)" % result)
            sys.exit(1)
    log("  database opened")

    # ---- Import IDA modules (only after db is open) ----
    import ida_auto
    import ida_funcs
    import ida_typeinf
    import idautils
    import idc

    has_decompiler = False
    try:
        import ida_hexrays
        has_decompiler = ida_hexrays.init_hexrays_plugin()
    except Exception:
        pass
    log("  decompiler: %s" % ("yes" if has_decompiler else "no"))

    # ---- Wait for auto-analysis ----
    log("Waiting for auto-analysis...")
    t0 = time.time()
    ida_auto.auto_wait()
    log("  done (%.1fs)" % (time.time() - t0))

    stats = apply_metadata(meta, idc, ida_funcs, ida_typeinf, ida_auto)

    # ================================================================
    # Phase 5: Decompile focus functions
    # ================================================================
    functions = meta.get("functions", [])
    focus = meta.get("focus_functions", [])
    decompiled = 0
    decompile_failed = 0

    if out_dir and focus and has_decompiler:
        log("Phase 5: decompiling %d focus functions..." % len(focus))
        if not os.path.exists(out_dir):
            os.makedirs(out_dir)

        name_by_addr = {}
        owner_by_addr = {}
        for entry in functions:
            a = entry["addr"]
            name_by_addr[a] = entry["name"]
            if entry.get("owner"):
                owner_by_addr[a] = entry["owner"]

        index = []
        for addr_str in focus:
            addr = int(addr_str, 16)
            fn = ida_funcs.get_func(addr)
            if fn is None:
                index.append({
                    "addr": addr_str,
                    "name": name_by_addr.get(addr_str, "unknown"),
                    "file": None,
                    "decompile_ok": False,
                    "reason": "no_function",
                })
                decompile_failed += 1
                continue

            fn_name = idc.get_func_name(fn.start_ea)
            try:
                cfunc = ida_hexrays.decompile(fn.start_ea)
                if cfunc is None:
                    raise Exception("decompile returned None")

                c_code = str(cfunc)

                safe_name = addr_str.replace("0x", "") + "_" + sanitize_filename(fn_name)
                owner = owner_by_addr.get(addr_str, "")
                if owner:
                    sub = sanitize_filename(owner)
                    sub_dir = os.path.join(out_dir, sub)
                    if not os.path.exists(sub_dir):
                        os.makedirs(sub_dir)
                    out_file = os.path.join(sub, safe_name + ".c")
                else:
                    out_file = safe_name + ".c"

                with open(os.path.join(out_dir, out_file), "w") as cf:
                    cf.write(c_code)

                index.append({
                    "addr": addr_str,
                    "name": fn_name,
                    "file": out_file,
                    "decompile_ok": True,
                })
                decompiled += 1
            except Exception as e:
                index.append({
                    "addr": addr_str,
                    "name": fn_name,
                    "file": None,
                    "decompile_ok": False,
                    "reason": str(e)[:100],
                })
                decompile_failed += 1

        with open(os.path.join(out_dir, "index.json"), "w") as idx:
            json.dump(index, idx, indent=2)
        log("  decompiled=%d failed=%d" % (decompiled, decompile_failed))
    elif not has_decompiler:
        log("Phase 5: skipped (no Hex-Rays)")
    elif not out_dir:
        log("Phase 5: skipped (no output dir)")
    else:
        log("Phase 5: skipped (no focus functions)")

    # ================================================================
    # Save and close
    # ================================================================
    log("Saving database...")
    idapro.close_database(1)

    log("DONE: created=%d named=%d structs=%d sigs=%d comments=%d "
        "decompiled=%d" % (
            stats["functions_created"],
            stats["functions_named"],
            stats["structs_created"],
            stats["signatures_applied"],
            stats["comments_set"],
            decompiled,
        ))


# ============================================================
# C header generation
# ============================================================

def build_class_struct(sname, size, fields, pointer_size):
    """Build an IL2CPP class struct as C declaration."""
    field_sz = pointer_size
    field_type = "int" if pointer_size == 4 else "void*"

    sorted_fields = sorted(fields, key=lambda f: f.get("byte_offset", 0))

    lines = ["struct %s {" % sname]
    prev_end = 0
    pad_idx = 0
    for f in sorted_fields:
        off = f.get("byte_offset", 0)
        fname = sanitize(f.get("name", "field_%x" % off))
        tname = f.get("type_name", "")
        if off < prev_end:
            continue
        if off > prev_end:
            lines.append("  char _pad%d[%d];" % (pad_idx, off - prev_end))
            pad_idx += 1
        # Use type info if available
        ctype = il2cpp_type_to_c(tname, field_type)
        if off + type_size(ctype, pointer_size) <= size:
            lines.append("  %s %s;" % (ctype, fname))
            prev_end = off + type_size(ctype, pointer_size)
        else:
            prev_end = off

    if prev_end < size:
        lines.append("  char _pad_tail[%d];" % (size - prev_end))

    lines.append("};")
    return "\n".join(lines)


def il2cpp_type_to_c(type_name, default):
    """Map IL2CPP type name to C type."""
    mapping = {
        "System.Boolean": "char",
        "System.Byte": "unsigned char",
        "System.SByte": "char",
        "System.Int16": "short",
        "System.UInt16": "unsigned short",
        "System.Int32": "int",
        "System.UInt32": "unsigned int",
        "System.Int64": "long long",
        "System.UInt64": "unsigned long long",
        "System.Single": "float",
        "System.Double": "double",
        "System.Char": "unsigned short",
        "System.IntPtr": "void*",
        "System.UIntPtr": "void*",
    }
    return mapping.get(type_name, default)


def type_size(ctype, pointer_size):
    """Return size of a C type."""
    sizes = {
        "char": 1,
        "unsigned char": 1,
        "short": 2,
        "unsigned short": 2,
        "int": 4,
        "unsigned int": 4,
        "long long": 8,
        "unsigned long long": 8,
        "float": 4,
        "double": 8,
        "void*": pointer_size,
    }
    return sizes.get(ctype, pointer_size)


def build_function_prototype(name, owner, param_count, return_type, is_static, struct_names):
    """Build C function prototype for IL2CPP method."""
    cname = sanitize(name)
    ret = il2cpp_type_to_c(return_type, "void*") if return_type else "void*"
    params = []

    # IL2CPP instance methods get a this pointer + MethodInfo*
    if owner and not is_static:
        if owner in struct_names:
            params.append("struct %s* this" % struct_names[owner])
        else:
            params.append("void* this")

    for i in range(param_count):
        params.append("void* p%d" % i)

    # IL2CPP always passes MethodInfo* as last hidden arg
    params.append("void* method")

    return "%s __fastcall %s(%s);" % (ret, cname, ", ".join(params))


if __name__ == "__main__":
    main()
