// Package output provides IL2CPP structure generation for il2cpp.h
package output

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"disunity/internal/binary"
	"disunity/internal/metadata"
)

// StructGenerator generates il2cpp.h from metadata and binary type information
type StructGenerator struct {
	meta    *metadata.GlobalMetadata
	types   []*binary.Il2CppType
	version float64

	// Name mappings
	structNameDic            map[int]string            // typeDefIndex -> struct name
	genericClassStructNames  map[uint64]string         // generic_class ptr -> struct name
	structNameHashSet        map[string]bool           // track generated struct names
	typeDefImageNames        map[int]string            // typeDefIndex -> image name
	genericInstNames         map[int]string            // type index -> generic instantiation name

	// VTable method names (slot index -> method name)
	vtableMethodNames map[int]map[int]string // typeDefIndex -> slot -> methodName

	// Array types tracking (type index -> array struct name)
	arrayTypeNames map[int]string        // SZARRAY type index -> array struct name
	arrayTypeElements map[int]string     // SZARRAY type index -> element type name

	// Generated output
	structInfoList []StructInfo

	// Static analyzer for reading generic class data from binary
	staticAnalyzer *binary.IL2CPPStaticAnalyzer

	// RGCTX data parsed from binary (for proper _RGCTXs generation)
	rgctxData *RGCTXData
}

// StructInfo holds information about a generated struct
type StructInfo struct {
	TypeName   string
	IsClass    bool
	Fields     []FieldInfo
	Parent     string
}

// FieldInfo holds information about a struct field
type FieldInfo struct {
	TypeName   string
	FieldName  string
	Offset     int32
}

// Reserved C/C++ keywords that need escaping
var cKeywords = map[string]bool{
	"klass": true, "monitor": true, "register": true, "_cs": true, "auto": true,
	"friend": true, "template": true, "flat": true, "default": true, "_ds": true,
	"interrupt": true, "unsigned": true, "signed": true, "asm": true, "if": true,
	"case": true, "break": true, "continue": true, "do": true, "new": true,
	"_": true, "short": true, "union": true, "class": true, "namespace": true,
	"inline": true, "near": true, "far": true, "int": true, "long": true,
	"float": true, "double": true, "char": true, "void": true, "bool": true,
	"const": true, "static": true, "extern": true, "volatile": true, "struct": true,
	"enum": true, "typedef": true, "return": true, "goto": true, "switch": true,
	"while": true, "for": true, "else": true, "sizeof": true, "typeof": true,
	"NULL": true, "null": true, "true": true, "false": true, "this": true,
}

// NewStructGenerator creates a new structure generator
func NewStructGenerator(meta *metadata.GlobalMetadata, types []*binary.Il2CppType, version float64) *StructGenerator {
	return &StructGenerator{
		meta:                    meta,
		types:                   types,
		version:                 version,
		structNameDic:           make(map[int]string),
		genericClassStructNames: make(map[uint64]string),
		structNameHashSet:       make(map[string]bool),
		typeDefImageNames:       make(map[int]string),
		genericInstNames:        make(map[int]string),
		vtableMethodNames:       make(map[int]map[int]string),
		arrayTypeNames:          make(map[int]string),
		arrayTypeElements:       make(map[int]string),
	}
}

// NewStructGeneratorWithAnalyzer creates a structure generator with a static analyzer
// for reading generic class data from the binary
func NewStructGeneratorWithAnalyzer(meta *metadata.GlobalMetadata, types []*binary.Il2CppType, version float64, analyzer *binary.IL2CPPStaticAnalyzer) *StructGenerator {
	g := NewStructGenerator(meta, types, version)
	g.staticAnalyzer = analyzer
	return g
}

// SetRGCTXData sets the RGCTX data parsed from the binary.
// This enables proper _RGCTXs struct generation with actual class/method references.
func (g *StructGenerator) SetRGCTXData(rgctx *RGCTXData) {
	g.rgctxData = rgctx
}

// GenerateHeader generates the il2cpp.h content
func (g *StructGenerator) GenerateHeader() string {
	var sb strings.Builder

	// Write header
	sb.WriteString("// Auto-generated IL2CPP structures\n")
	sb.WriteString("// Generated by disunity\n\n")
	sb.WriteString("#pragma once\n\n")
	sb.WriteString("#include <stdint.h>\n")
	sb.WriteString("#include <stdbool.h>\n")
	sb.WriteString("#include <stddef.h>\n\n")

	// Write base IL2CPP types
	g.writeBaseTypes(&sb)

	// Build unique struct names for all type definitions
	g.buildStructNames()

	// Build vtable method name mappings
	g.buildVTableMethodNames()

	// Build generic instantiation names
	g.buildGenericInstNames()

	// Build array type names (SZARRAY types)
	g.buildArrayTypeNames()

	// Generate structs for all types
	g.generateAllStructs(&sb)

	// Generate array type structs
	g.generateArrayStructs(&sb)

	// Generate generic instantiation structs
	g.generateGenericInstStructs(&sb)

	return sb.String()
}

// ClassCount returns the number of generated struct names.
// Must be called after GenerateHeader().
func (g *StructGenerator) ClassCount() int {
	return len(g.structNameDic)
}

// writeBaseTypes writes the fundamental IL2CPP types (matching Il2CppDumper output)
func (g *StructGenerator) writeBaseTypes(sb *strings.Builder) {
	sb.WriteString("// IL2CPP function pointer type\n")
	sb.WriteString("typedef void(*Il2CppMethodPointer)();\n\n")

	sb.WriteString("struct MethodInfo;\n\n")

	sb.WriteString("struct VirtualInvokeData\n")
	sb.WriteString("{\n")
	sb.WriteString("    Il2CppMethodPointer methodPtr;\n")
	sb.WriteString("    const struct MethodInfo* method;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("struct Il2CppType\n")
	sb.WriteString("{\n")
	sb.WriteString("    void* data;\n")
	sb.WriteString("    unsigned int bits;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("struct Il2CppClass;\n\n")

	sb.WriteString("struct Il2CppObject\n")
	sb.WriteString("{\n")
	sb.WriteString("    struct Il2CppClass *klass;\n")
	sb.WriteString("    void *monitor;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("union Il2CppRGCTXData\n")
	sb.WriteString("{\n")
	sb.WriteString("    void* rgctxDataDummy;\n")
	sb.WriteString("    const struct MethodInfo* method;\n")
	sb.WriteString("    const struct Il2CppType* type;\n")
	sb.WriteString("    struct Il2CppClass* klass;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("struct Il2CppRuntimeInterfaceOffsetPair\n")
	sb.WriteString("{\n")
	sb.WriteString("    struct Il2CppClass* interfaceType;\n")
	sb.WriteString("    int32_t offset;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("struct Il2CppClass_1\n")
	sb.WriteString("{\n")
	sb.WriteString("    void* image;\n")
	sb.WriteString("    void* gc_desc;\n")
	sb.WriteString("    const char* name;\n")
	sb.WriteString("    const char* namespaze;\n")
	sb.WriteString("    struct Il2CppType byval_arg;\n")
	sb.WriteString("    struct Il2CppType this_arg;\n")
	sb.WriteString("    struct Il2CppClass* element_class;\n")
	sb.WriteString("    struct Il2CppClass* castClass;\n")
	sb.WriteString("    struct Il2CppClass* declaringType;\n")
	sb.WriteString("    struct Il2CppClass* parent;\n")
	sb.WriteString("    void *generic_class;\n")
	sb.WriteString("    void* typeDefinition;\n")
	sb.WriteString("    void* interopData;\n")
	sb.WriteString("    struct Il2CppClass* klass;\n")
	sb.WriteString("    void* fields;\n")
	sb.WriteString("    void* events;\n")
	sb.WriteString("    void* properties;\n")
	sb.WriteString("    void* methods;\n")
	sb.WriteString("    struct Il2CppClass** nestedTypes;\n")
	sb.WriteString("    struct Il2CppClass** implementedInterfaces;\n")
	sb.WriteString("    struct Il2CppRuntimeInterfaceOffsetPair* interfaceOffsets;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("struct Il2CppClass_2\n")
	sb.WriteString("{\n")
	sb.WriteString("    struct Il2CppClass** typeHierarchy;\n")
	sb.WriteString("    void *unity_user_data;\n")
	sb.WriteString("    uint32_t initializationExceptionGCHandle;\n")
	sb.WriteString("    uint32_t cctor_started;\n")
	sb.WriteString("    uint32_t cctor_finished;\n")
	sb.WriteString("    size_t cctor_thread;\n")
	sb.WriteString("    int32_t genericContainerIndex;\n")
	sb.WriteString("    uint32_t instance_size;\n")
	sb.WriteString("    uint32_t actualSize;\n")
	sb.WriteString("    uint32_t element_size;\n")
	sb.WriteString("    int32_t native_size;\n")
	sb.WriteString("    uint32_t static_fields_size;\n")
	sb.WriteString("    uint32_t thread_static_fields_size;\n")
	sb.WriteString("    int32_t thread_static_fields_offset;\n")
	sb.WriteString("    uint32_t flags;\n")
	sb.WriteString("    uint32_t token;\n")
	sb.WriteString("    uint16_t method_count;\n")
	sb.WriteString("    uint16_t property_count;\n")
	sb.WriteString("    uint16_t field_count;\n")
	sb.WriteString("    uint16_t event_count;\n")
	sb.WriteString("    uint16_t nested_type_count;\n")
	sb.WriteString("    uint16_t vtable_count;\n")
	sb.WriteString("    uint16_t interfaces_count;\n")
	sb.WriteString("    uint16_t interface_offsets_count;\n")
	sb.WriteString("    uint8_t typeHierarchyDepth;\n")
	sb.WriteString("    uint8_t genericRecursionDepth;\n")
	sb.WriteString("    uint8_t rank;\n")
	sb.WriteString("    uint8_t minimumAlignment;\n")
	sb.WriteString("    uint8_t naturalAligment;\n")
	sb.WriteString("    uint8_t packingSize;\n")
	sb.WriteString("    uint8_t bitflags1;\n")
	sb.WriteString("    uint8_t bitflags2;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("struct Il2CppClass\n")
	sb.WriteString("{\n")
	sb.WriteString("    struct Il2CppClass_1 _1;\n")
	sb.WriteString("    void* static_fields;\n")
	sb.WriteString("    union Il2CppRGCTXData* rgctx_data;\n")
	sb.WriteString("    struct Il2CppClass_2 _2;\n")
	sb.WriteString("    struct VirtualInvokeData vtable[255];\n")
	sb.WriteString("};\n\n")

	sb.WriteString("typedef uintptr_t il2cpp_array_size_t;\n")
	sb.WriteString("typedef int32_t il2cpp_array_lower_bound_t;\n")
	sb.WriteString("struct Il2CppArrayBounds\n")
	sb.WriteString("{\n")
	sb.WriteString("    il2cpp_array_size_t length;\n")
	sb.WriteString("    il2cpp_array_lower_bound_t lower_bound;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("struct MethodInfo\n")
	sb.WriteString("{\n")
	sb.WriteString("    Il2CppMethodPointer methodPointer;\n")
	sb.WriteString("    void* invoker_method;\n")
	sb.WriteString("    const char* name;\n")
	sb.WriteString("    struct Il2CppClass *klass;\n")
	sb.WriteString("    const struct Il2CppType *return_type;\n")
	sb.WriteString("    const void* parameters;\n")
	sb.WriteString("    union\n")
	sb.WriteString("    {\n")
	sb.WriteString("        const union Il2CppRGCTXData* rgctx_data;\n")
	sb.WriteString("        const void* methodDefinition;\n")
	sb.WriteString("    };\n")
	sb.WriteString("    union\n")
	sb.WriteString("    {\n")
	sb.WriteString("        const void* genericMethod;\n")
	sb.WriteString("        const void* genericContainer;\n")
	sb.WriteString("    };\n")
	sb.WriteString("    uint32_t token;\n")
	sb.WriteString("    uint16_t flags;\n")
	sb.WriteString("    uint16_t iflags;\n")
	sb.WriteString("    uint16_t slot;\n")
	sb.WriteString("    uint8_t parameters_count;\n")
	sb.WriteString("    uint8_t bitflags;\n")
	sb.WriteString("};\n\n")

	sb.WriteString("struct Il2CppString\n")
	sb.WriteString("{\n")
	sb.WriteString("    struct Il2CppObject object;\n")
	sb.WriteString("    int32_t length;\n")
	sb.WriteString("    uint16_t chars[1]; // variable length\n")
	sb.WriteString("};\n\n")

	sb.WriteString("struct Il2CppArray\n")
	sb.WriteString("{\n")
	sb.WriteString("    struct Il2CppObject object;\n")
	sb.WriteString("    struct Il2CppArrayBounds* bounds;\n")
	sb.WriteString("    il2cpp_array_size_t max_length;\n")
	sb.WriteString("};\n\n")

	// System_String alias
	sb.WriteString("typedef struct Il2CppString System_String_o;\n\n")
}

// buildStructNames creates unique struct names for all type definitions
func (g *StructGenerator) buildStructNames() {
	// First pass: map types to their image names
	for _, img := range g.meta.ImageDefinitions {
		imageName := g.meta.GetString(img.NameIndex)
		typeEnd := img.TypeStart + int32(img.TypeCount)
		for typeIndex := img.TypeStart; typeIndex < typeEnd; typeIndex++ {
			g.typeDefImageNames[int(typeIndex)] = imageName
		}
	}

	// Second pass: build unique struct names
	for i, typeDef := range g.meta.TypeDefinitions {
		g.createStructName(i, typeDef)
	}
}

// createStructName creates a unique struct name for a type definition
func (g *StructGenerator) createStructName(index int, typeDef *metadata.TypeDefinition) {
	namespace := g.meta.GetString(typeDef.NamespaceIndex)
	name := g.meta.GetString(typeDef.NameIndex)

	// Build full name: namespace + type name
	var fullName string
	if namespace != "" {
		fullName = namespace + "_" + name
	} else {
		fullName = name
	}

	// Handle nested types
	if typeDef.DeclaringTypeIndex >= 0 && int(typeDef.DeclaringTypeIndex) < len(g.meta.TypeDefinitions) {
		parentDef := g.meta.TypeDefinitions[typeDef.DeclaringTypeIndex]
		parentName := g.meta.GetString(parentDef.NameIndex)
		fullName = parentName + "_" + name
	}

	// Fix invalid characters
	structName := fixName(fullName)

	// Ensure uniqueness
	baseName := structName
	counter := 1
	for g.structNameHashSet[structName] {
		structName = fmt.Sprintf("%s_%d", baseName, counter)
		counter++
	}

	g.structNameHashSet[structName] = true
	g.structNameDic[index] = structName
}

// buildVTableMethodNames builds a mapping of vtable slot indices to method names
// This enables generating _VTable structs with named entries instead of arrays
// Uses the complete vtable from metadata (includes inherited and interface methods)
func (g *StructGenerator) buildVTableMethodNames() {
	// For each type definition, collect the method names for ALL vtable slots
	// using the VTableMethodIndices array from metadata
	for typeIdx, typeDef := range g.meta.TypeDefinitions {
		if typeDef == nil || typeDef.VtableCount == 0 {
			continue
		}

		g.vtableMethodNames[typeIdx] = make(map[int]string)

		// Use the vtable metadata to get ALL methods (inherited + interface + local)
		vtableStart := int(typeDef.VtableStart)
		vtableCount := int(typeDef.VtableCount)

		for slot := 0; slot < vtableCount; slot++ {
			vtableIdx := vtableStart + slot
			if vtableIdx < 0 || vtableIdx >= len(g.meta.VTableMethodIndices) {
				continue
			}

			encoded := g.meta.VTableMethodIndices[vtableIdx]
			methodIdx, _ := metadata.DecodeVTableMethodIndex(encoded)

			if methodIdx >= 0 && methodIdx < len(g.meta.MethodDefinitions) {
				methodName := g.meta.GetMethodName(methodIdx)
				if methodName != "" {
					g.vtableMethodNames[typeIdx][slot] = methodName
				}
			}
		}
	}
}

// buildGenericInstNames builds names for generic instantiation types
// e.g., List<int> -> List_1_int32_t, Dictionary<string, int> -> Dictionary_2_string_int32_t
func (g *StructGenerator) buildGenericInstNames() {
	for i, t := range g.types {
		if t == nil || t.Type != binary.IL2CPP_TYPE_GENERICINST {
			continue
		}

		// Generate a name for this generic instantiation
		name := g.buildGenericInstName(t)
		if name != "" {
			g.genericInstNames[i] = name
		}
	}
}

// buildGenericInstName builds a name for a generic instantiation type
func (g *StructGenerator) buildGenericInstName(t *binary.Il2CppType) string {
	if t == nil || g.staticAnalyzer == nil {
		return ""
	}

	// For GENERICINST, Data is a pointer to Il2CppGenericClass
	gcPtr := t.Data
	if gcPtr == 0 {
		return ""
	}

	// Read the generic class from the binary
	gc, err := g.staticAnalyzer.ReadGenericClass(gcPtr)
	if err != nil {
		return ""
	}

	// Get the base type name
	var baseName string
	if g.version < 27 {
		// v24.5 and below: has typeDefinitionIndex directly
		if gc.TypeDefinitionIndex >= 0 && int(gc.TypeDefinitionIndex) < len(g.meta.TypeDefinitions) {
			baseName = g.structNameDic[int(gc.TypeDefinitionIndex)]
		}
	} else {
		// v27+: has type pointer, need to resolve it
		if gc.Type != 0 {
			baseType, err := g.staticAnalyzer.GetIl2CppType(gc.Type)
			if err == nil && baseType != nil {
				if baseType.Type == binary.IL2CPP_TYPE_CLASS || baseType.Type == binary.IL2CPP_TYPE_VALUETYPE {
					klassIndex := int(baseType.Data)
					if klassIndex >= 0 && klassIndex < len(g.meta.TypeDefinitions) {
						baseName = g.structNameDic[klassIndex]
					}
				}
			}
		}
	}

	if baseName == "" {
		return ""
	}

	// Build type argument suffix
	var argNames []string
	if gc.ClassInst != 0 {
		gi, err := g.staticAnalyzer.ReadGenericInst(gc.ClassInst)
		if err == nil && gi != nil {
			for _, argPtr := range gi.TypeArgv {
				if argPtr == 0 {
					continue
				}
				argType, err := g.staticAnalyzer.GetIl2CppType(argPtr)
				if err == nil && argType != nil {
					argName := g.getTypeShortName(argType)
					if argName != "" {
						argNames = append(argNames, argName)
					}
				}
			}
		}
	}

	if len(argNames) == 0 {
		return baseName
	}

	// Format: BaseName_Arg1__Arg2 (matching Il2CppDumper's double underscore separator)
	return baseName + "_" + strings.Join(argNames, "__")
}

// buildArrayTypeNames builds names for SZARRAY types used in field declarations
// e.g., System.Byte[] -> System_Byte_array
func (g *StructGenerator) buildArrayTypeNames() {
	seenArrayNames := make(map[string]bool)

	for i, t := range g.types {
		if t == nil || t.Type != binary.IL2CPP_TYPE_SZARRAY {
			continue
		}

		// Get the element type name
		elementTypeName, elementCType := g.getArrayElementInfo(t)
		if elementTypeName == "" {
			continue
		}

		// Build array struct name: ElementTypeName_array
		arrayName := elementTypeName + "_array"

		// Avoid duplicates
		if seenArrayNames[arrayName] {
			continue
		}
		seenArrayNames[arrayName] = true

		g.arrayTypeNames[i] = arrayName
		g.arrayTypeElements[i] = elementCType
	}
}

// getArrayElementInfo returns the struct name and C type for an array element
func (g *StructGenerator) getArrayElementInfo(t *binary.Il2CppType) (string, string) {
	if t == nil || t.Type != binary.IL2CPP_TYPE_SZARRAY {
		return "", ""
	}

	// For SZARRAY, Data is a POINTER to Il2CppType, not a type index
	// We need to read the element type from the binary using the static analyzer
	var elemType *binary.Il2CppType

	if g.staticAnalyzer != nil && t.Data != 0 {
		var err error
		elemType, err = g.staticAnalyzer.GetIl2CppType(t.Data)
		if err != nil {
			// Fallback: maybe Data is actually an index in some versions?
			elemTypeIdx := int(t.Data)
			if elemTypeIdx >= 0 && elemTypeIdx < len(g.types) && g.types[elemTypeIdx] != nil {
				elemType = g.types[elemTypeIdx]
			}
		}
	} else {
		// Fallback: try treating Data as type index
		elemTypeIdx := int(t.Data)
		if elemTypeIdx >= 0 && elemTypeIdx < len(g.types) && g.types[elemTypeIdx] != nil {
			elemType = g.types[elemTypeIdx]
		}
	}

	if elemType == nil {
		return "System_Object", "struct Il2CppObject*"
	}

	switch elemType.Type {
	case binary.IL2CPP_TYPE_BOOLEAN:
		return "System_Boolean", "bool"
	case binary.IL2CPP_TYPE_CHAR:
		return "System_Char", "uint16_t"
	case binary.IL2CPP_TYPE_I1:
		return "System_SByte", "int8_t"
	case binary.IL2CPP_TYPE_U1:
		return "System_Byte", "uint8_t"
	case binary.IL2CPP_TYPE_I2:
		return "System_Int16", "int16_t"
	case binary.IL2CPP_TYPE_U2:
		return "System_UInt16", "uint16_t"
	case binary.IL2CPP_TYPE_I4:
		return "System_Int32", "int32_t"
	case binary.IL2CPP_TYPE_U4:
		return "System_UInt32", "uint32_t"
	case binary.IL2CPP_TYPE_I8:
		return "System_Int64", "int64_t"
	case binary.IL2CPP_TYPE_U8:
		return "System_UInt64", "uint64_t"
	case binary.IL2CPP_TYPE_R4:
		return "System_Single", "float"
	case binary.IL2CPP_TYPE_R8:
		return "System_Double", "double"
	case binary.IL2CPP_TYPE_STRING:
		return "System_String", "System_String_o*"
	case binary.IL2CPP_TYPE_I:
		return "System_IntPtr", "intptr_t"
	case binary.IL2CPP_TYPE_U:
		return "System_UIntPtr", "uintptr_t"
	case binary.IL2CPP_TYPE_OBJECT:
		return "System_Object", "struct Il2CppObject*"
	case binary.IL2CPP_TYPE_VALUETYPE:
		klassIndex := int(elemType.Data)
		if name := g.structNameDic[klassIndex]; name != "" {
			return name, name + "_o"
		}
		return "System_Object", "struct Il2CppObject*"
	case binary.IL2CPP_TYPE_CLASS:
		klassIndex := int(elemType.Data)
		if name := g.structNameDic[klassIndex]; name != "" {
			return name, name + "_o*"
		}
		return "System_Object", "struct Il2CppObject*"
	case binary.IL2CPP_TYPE_GENERICINST:
		// For generic instantiation element types, we can't easily look up the name
		// without the type index. Fall back to generic pointer type.
		// TODO: Build a reverse lookup from element type pointer to instantiation name
		return "System_Object", "struct Il2CppObject*"
	case binary.IL2CPP_TYPE_SZARRAY:
		// Nested array - rare but possible
		return "System_Array", "struct Il2CppArray*"
	default:
		return "System_Object", "struct Il2CppObject*"
	}
}

// generateArrayStructs generates struct definitions for all array types
func (g *StructGenerator) generateArrayStructs(sb *strings.Builder) {
	if len(g.arrayTypeNames) == 0 {
		return
	}

	sb.WriteString("\n// Array type structs\n")

	// Collect unique array type definitions
	type arrayDef struct {
		name        string
		elementType string
	}
	seen := make(map[string]bool)
	var arrays []arrayDef

	for typeIdx, name := range g.arrayTypeNames {
		if seen[name] {
			continue
		}
		seen[name] = true
		arrays = append(arrays, arrayDef{name, g.arrayTypeElements[typeIdx]})
	}

	// Sort for consistent output
	sort.Slice(arrays, func(i, j int) bool {
		return arrays[i].name < arrays[j].name
	})

	// Generate array structs
	for _, arr := range arrays {
		sb.WriteString(fmt.Sprintf("struct %s {\n", arr.name))
		sb.WriteString("\tIl2CppObject obj;\n")
		sb.WriteString("\tIl2CppArrayBounds *bounds;\n")
		sb.WriteString("\til2cpp_array_size_t max_length;\n")
		sb.WriteString(fmt.Sprintf("\t%s m_Items[65535];\n", arr.elementType))
		sb.WriteString("};\n")
	}
}

// getTypeShortName returns a short C-compatible name for a type
func (g *StructGenerator) getTypeShortName(t *binary.Il2CppType) string {
	if t == nil {
		return "void"
	}

	switch t.Type {
	case binary.IL2CPP_TYPE_VOID:
		return "void"
	case binary.IL2CPP_TYPE_BOOLEAN:
		return "bool"
	case binary.IL2CPP_TYPE_CHAR:
		return "char16"
	case binary.IL2CPP_TYPE_I1:
		return "int8"
	case binary.IL2CPP_TYPE_U1:
		return "uint8"
	case binary.IL2CPP_TYPE_I2:
		return "int16"
	case binary.IL2CPP_TYPE_U2:
		return "uint16"
	case binary.IL2CPP_TYPE_I4:
		return "int32"
	case binary.IL2CPP_TYPE_U4:
		return "uint32"
	case binary.IL2CPP_TYPE_I8:
		return "int64"
	case binary.IL2CPP_TYPE_U8:
		return "uint64"
	case binary.IL2CPP_TYPE_R4:
		return "float"
	case binary.IL2CPP_TYPE_R8:
		return "double"
	case binary.IL2CPP_TYPE_STRING:
		return "string"
	case binary.IL2CPP_TYPE_I:
		return "intptr"
	case binary.IL2CPP_TYPE_U:
		return "uintptr"
	case binary.IL2CPP_TYPE_OBJECT:
		return "object"
	case binary.IL2CPP_TYPE_VALUETYPE, binary.IL2CPP_TYPE_CLASS:
		klassIndex := int(t.Data)
		if name := g.structNameDic[klassIndex]; name != "" {
			return name
		}
		return "object"
	case binary.IL2CPP_TYPE_SZARRAY:
		return "array"
	case binary.IL2CPP_TYPE_ARRAY:
		return "array"
	case binary.IL2CPP_TYPE_GENERICINST:
		// Recursively get generic instantiation name
		return "generic"
	case binary.IL2CPP_TYPE_VAR, binary.IL2CPP_TYPE_MVAR:
		return "T"
	default:
		return "void"
	}
}

// generateAllStructs generates struct definitions for all types
func (g *StructGenerator) generateAllStructs(sb *strings.Builder) {
	sb.WriteString("// Forward declarations\n")

	// Collect all struct names for forward declarations
	var names []string
	for _, name := range g.structNameDic {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		sb.WriteString(fmt.Sprintf("struct %s_o;\n", name))
		sb.WriteString(fmt.Sprintf("struct %s_Fields;\n", name))
		sb.WriteString(fmt.Sprintf("struct %s_c;\n", name))
		sb.WriteString(fmt.Sprintf("struct %s_StaticFields;\n", name))
	}
	sb.WriteString("\n")

	// Forward declarations for array types
	if len(g.arrayTypeNames) > 0 {
		sb.WriteString("// Array type forward declarations\n")
		seenArrayNames := make(map[string]bool)
		var arrayNames []string
		for _, name := range g.arrayTypeNames {
			if !seenArrayNames[name] {
				seenArrayNames[name] = true
				arrayNames = append(arrayNames, name)
			}
		}
		sort.Strings(arrayNames)
		for _, name := range arrayNames {
			sb.WriteString(fmt.Sprintf("struct %s;\n", name))
		}
		sb.WriteString("\n")
	}

	// Generate struct definitions
	sb.WriteString("// Struct definitions\n")
	for i, typeDef := range g.meta.TypeDefinitions {
		g.generateTypeStruct(sb, i, typeDef)
	}
}

// generateTypeStruct generates the struct definition for a single type
func (g *StructGenerator) generateTypeStruct(sb *strings.Builder, index int, typeDef *metadata.TypeDefinition) {
	structName := g.structNameDic[index]
	if structName == "" {
		return
	}

	isValueType := (typeDef.BitField & 0x1) != 0 // Check IsValueType bit

	// Collect instance and static fields separately
	var instanceFields []struct {
		name     string
		typeName string
	}
	var staticFields []struct {
		name     string
		typeName string
	}

	if typeDef.FieldCount > 0 && typeDef.FieldStart >= 0 {
		usedNames := make(map[string]int)
		fieldEnd := typeDef.FieldStart + int32(typeDef.FieldCount)
		for fieldIdx := typeDef.FieldStart; fieldIdx < fieldEnd; fieldIdx++ {
			if fieldIdx < 0 || int(fieldIdx) >= len(g.meta.FieldDefinitions) {
				continue
			}
			field := g.meta.FieldDefinitions[fieldIdx]
			if field == nil {
				continue
			}
			fieldName := fixName(g.meta.GetFieldName(int(fieldIdx)))
			fieldType := g.parseTypeIndex(field.TypeIndex)

			// Handle duplicate names
			baseName := fieldName
			if count, exists := usedNames[baseName]; exists {
				fieldName = fmt.Sprintf("%s_%d", baseName, count)
				usedNames[baseName] = count + 1
			} else {
				usedNames[baseName] = 1
			}

			// Check if field is static via type attributes
			isStatic := false
			if field.TypeIndex >= 0 && int(field.TypeIndex) < len(g.types) && g.types[field.TypeIndex] != nil {
				// FIELD_ATTRIBUTE_STATIC = 0x0010 in attrs
				isStatic = (g.types[field.TypeIndex].Attrs & 0x0010) != 0
			}

			entry := struct {
				name     string
				typeName string
			}{fieldName, fieldType}

			if isStatic {
				staticFields = append(staticFields, entry)
			} else {
				instanceFields = append(instanceFields, entry)
			}
		}
	}

	// Generate _Fields struct (instance fields only)
	sb.WriteString(fmt.Sprintf("// %s\n", g.getFullTypeName(typeDef)))
	sb.WriteString(fmt.Sprintf("struct %s_Fields {\n", structName))

	if len(instanceFields) > 0 {
		for _, f := range instanceFields {
			sb.WriteString(fmt.Sprintf("    %s %s;\n", f.typeName, f.name))
		}
	} else if typeDef.ParentIndex < 0 {
		sb.WriteString("    uint8_t __dummy; // empty struct placeholder\n")
	}

	sb.WriteString("};\n")

	// Generate _StaticFields struct if there are static fields
	if len(staticFields) > 0 {
		sb.WriteString(fmt.Sprintf("struct %s_StaticFields {\n", structName))
		for _, f := range staticFields {
			sb.WriteString(fmt.Sprintf("    %s %s;\n", f.typeName, f.name))
		}
		sb.WriteString("};\n")
	}

	// Generate _VTable struct with named entries
	vtableCount := int(typeDef.VtableCount)
	if vtableCount > 0 {
		g.generateVTableStruct(sb, structName, index, vtableCount)
	}

	// Generate _RGCTXs struct if this type has generic context data
	if typeDef.GenericContainerIndex >= 0 {
		g.generateRGCTXsStruct(sb, structName, index)
	}

	// Generate _c struct (class metadata with VTable)
	// VTable size is based on vtable_count from TypeDefinition
	if vtableCount == 0 {
		vtableCount = 4 // Minimum: Object's 4 virtual methods
	}
	if vtableCount > 255 {
		vtableCount = 255 // Cap at reasonable max
	}

	sb.WriteString(fmt.Sprintf("struct %s_c {\n", structName))
	sb.WriteString("    struct Il2CppClass_1 _1;\n")
	if len(staticFields) > 0 {
		sb.WriteString(fmt.Sprintf("    struct %s_StaticFields* static_fields;\n", structName))
	} else {
		sb.WriteString("    void* static_fields;\n")
	}
	// Use typed RGCTXs if generated
	if typeDef.GenericContainerIndex >= 0 {
		sb.WriteString(fmt.Sprintf("    struct %s_RGCTXs* rgctx_data;\n", structName))
	} else {
		sb.WriteString("    union Il2CppRGCTXData* rgctx_data;\n")
	}
	sb.WriteString("    struct Il2CppClass_2 _2;\n")
	// Use typed VTable if generated
	if vtableCount > 0 && g.hasNamedVTableEntries(index) {
		sb.WriteString(fmt.Sprintf("    struct %s_VTable vtable;\n", structName))
	} else {
		sb.WriteString(fmt.Sprintf("    struct VirtualInvokeData vtable[%d];\n", vtableCount))
	}
	sb.WriteString("};\n")

	// Generate _o struct (object wrapper)
	sb.WriteString(fmt.Sprintf("struct %s_o {\n", structName))
	if isValueType {
		sb.WriteString(fmt.Sprintf("    struct %s_Fields fields;\n", structName))
	} else {
		sb.WriteString(fmt.Sprintf("    struct %s_c* klass;\n", structName))
		sb.WriteString("    void* monitor;\n")
		sb.WriteString(fmt.Sprintf("    struct %s_Fields fields;\n", structName))
	}
	sb.WriteString("};\n\n")
}

// getFullTypeName returns the full type name (namespace.type)
func (g *StructGenerator) getFullTypeName(typeDef *metadata.TypeDefinition) string {
	namespace := g.meta.GetString(typeDef.NamespaceIndex)
	name := g.meta.GetString(typeDef.NameIndex)
	if namespace != "" {
		return namespace + "." + name
	}
	return name
}

// ParseTypeIndex converts an Il2CppType index to a C type string.
func (g *StructGenerator) ParseTypeIndex(typeIndex int32) string {
	return g.parseTypeIndex(typeIndex)
}

// parseTypeIndex converts an Il2CppType index to a C type string
func (g *StructGenerator) parseTypeIndex(typeIndex int32) string {
	if typeIndex < 0 || int(typeIndex) >= len(g.types) || g.types[typeIndex] == nil {
		return "void*"
	}

	// Check if this is an SZARRAY type with a known array struct name
	if name := g.arrayTypeNames[int(typeIndex)]; name != "" {
		return "struct " + name + "*"
	}

	return g.parseTypeWithIndex(g.types[typeIndex], int(typeIndex))
}

// parseTypeWithIndex converts an Il2CppType to a C type string, with type index for lookups
func (g *StructGenerator) parseTypeWithIndex(t *binary.Il2CppType, typeIdx int) string {
	if t == nil {
		return "void*"
	}

	// Check for array types first
	if t.Type == binary.IL2CPP_TYPE_SZARRAY {
		// Try to find or create an array type name
		elementName, _ := g.getArrayElementInfo(t)
		if elementName != "" {
			return "struct " + elementName + "_array*"
		}
		return "struct Il2CppArray*"
	}

	return g.parseType(t)
}

// parseType converts an Il2CppType to a C type string
func (g *StructGenerator) parseType(t *binary.Il2CppType) string {
	if t == nil {
		return "void*"
	}

	switch t.Type {
	case binary.IL2CPP_TYPE_VOID:
		return "void"
	case binary.IL2CPP_TYPE_BOOLEAN:
		return "bool"
	case binary.IL2CPP_TYPE_CHAR:
		return "uint16_t" // Il2CppChar is UTF-16
	case binary.IL2CPP_TYPE_I1:
		return "int8_t"
	case binary.IL2CPP_TYPE_U1:
		return "uint8_t"
	case binary.IL2CPP_TYPE_I2:
		return "int16_t"
	case binary.IL2CPP_TYPE_U2:
		return "uint16_t"
	case binary.IL2CPP_TYPE_I4:
		return "int32_t"
	case binary.IL2CPP_TYPE_U4:
		return "uint32_t"
	case binary.IL2CPP_TYPE_I8:
		return "int64_t"
	case binary.IL2CPP_TYPE_U8:
		return "uint64_t"
	case binary.IL2CPP_TYPE_R4:
		return "float"
	case binary.IL2CPP_TYPE_R8:
		return "double"
	case binary.IL2CPP_TYPE_STRING:
		return "System_String_o*"
	case binary.IL2CPP_TYPE_PTR:
		// Pointer to another type - would need to read the nested type
		return "void*"
	case binary.IL2CPP_TYPE_VALUETYPE:
		// Value type - data contains klassIndex
		klassIndex := int(t.Data)
		if klassIndex >= 0 && klassIndex < len(g.meta.TypeDefinitions) {
			typeDef := g.meta.TypeDefinitions[klassIndex]
			// Check if it's an enum - ElementTypeIndex points to underlying type
			// For enums, this should be a primitive type (I4, U4, etc.)
			if typeDef.ElementTypeIndex >= 0 && int(typeDef.ElementTypeIndex) < len(g.types) {
				elemType := g.types[typeDef.ElementTypeIndex]
				// Only recurse for primitive types to avoid cycles
				if elemType != nil && elemType.Type >= binary.IL2CPP_TYPE_BOOLEAN && elemType.Type <= binary.IL2CPP_TYPE_R8 {
					return g.parseType(elemType)
				}
			}
			if name := g.structNameDic[klassIndex]; name != "" {
				// Use pointer for value types to avoid forward declaration issues
				// (proper fix would require topological sorting of type definitions)
				return "struct " + name + "_o*"
			}
		}
		return "void*"
	case binary.IL2CPP_TYPE_CLASS:
		// Class type - data contains klassIndex
		klassIndex := int(t.Data)
		if name := g.structNameDic[klassIndex]; name != "" {
			return "struct " + name + "_o*"
		}
		return "struct Il2CppObject*"
	case binary.IL2CPP_TYPE_VAR:
		// Generic type variable (T) - fall back to object
		return "struct Il2CppObject*"
	case binary.IL2CPP_TYPE_ARRAY:
		// Multi-dimensional array
		return "struct Il2CppArray*"
	case binary.IL2CPP_TYPE_GENERICINST:
		// Generic instantiation - would need generic class resolution
		return "void*"
	case binary.IL2CPP_TYPE_TYPEDBYREF:
		return "struct Il2CppObject*"
	case binary.IL2CPP_TYPE_I:
		return "intptr_t"
	case binary.IL2CPP_TYPE_U:
		return "uintptr_t"
	case binary.IL2CPP_TYPE_OBJECT:
		return "struct Il2CppObject*"
	case binary.IL2CPP_TYPE_SZARRAY:
		// Single-dimensional array
		return "struct Il2CppArray*"
	case binary.IL2CPP_TYPE_MVAR:
		// Generic method type variable
		return "struct Il2CppObject*"
	default:
		return "void*"
	}
}

// generateVTableStruct generates a _VTable struct with named entries
// Format matches Il2CppDumper: _N_MethodName where N is the slot number
func (g *StructGenerator) generateVTableStruct(sb *strings.Builder, structName string, typeDefIndex int, vtableCount int) {
	methodNames := g.vtableMethodNames[typeDefIndex]
	if len(methodNames) == 0 {
		return // No named vtable entries to generate
	}

	sb.WriteString(fmt.Sprintf("struct %s_VTable {\n", structName))

	// Generate named entries for each vtable slot
	// Format: _N_MethodName (matching Il2CppDumper output)
	for slot := 0; slot < vtableCount; slot++ {
		methodName := methodNames[slot]
		var entryName string
		if methodName == "" {
			// Unnamed slot - use "unknown" like Il2CppDumper
			entryName = fmt.Sprintf("_%d_unknown", slot)
		} else {
			entryName = fmt.Sprintf("_%d_%s", slot, fixName(methodName))
		}

		sb.WriteString(fmt.Sprintf("\tVirtualInvokeData %s;\n", entryName))
	}

	sb.WriteString("};\n")
}

// hasNamedVTableEntries returns true if the type has any named vtable entries
func (g *StructGenerator) hasNamedVTableEntries(typeDefIndex int) bool {
	return len(g.vtableMethodNames[typeDefIndex]) > 0
}

// generateRGCTXsStruct generates a _RGCTXs struct for runtime generic context
// Format matches Il2CppDumper: uses _N_TypeOrMethodName entries
func (g *StructGenerator) generateRGCTXsStruct(sb *strings.Builder, structName string, typeDefIndex int) {
	typeDef := g.meta.TypeDefinitions[typeDefIndex]
	if typeDef == nil || typeDef.GenericContainerIndex < 0 {
		return
	}

	// Get the generic container to determine type parameters
	if int(typeDef.GenericContainerIndex) >= len(g.meta.GenericContainers) {
		return
	}
	container := g.meta.GenericContainers[typeDef.GenericContainerIndex]
	if container == nil {
		return
	}

	sb.WriteString(fmt.Sprintf("struct %s_RGCTXs {\n", structName))

	// Try to use actual RGCTX data from binary (Il2CppDumper parity)
	if g.rgctxData != nil {
		entries := g.rgctxData.GetRGCTXEntries(typeDefIndex, g.meta)
		if len(entries) > 0 {
			for _, entry := range entries {
				sb.WriteString(fmt.Sprintf("\t%s _%d_%s;\n", entry.TypeName, entry.Index, entry.Name))
			}
			sb.WriteString("};\n")
			return
		}
	}

	// Fallback: generate entries based on generic type parameters only
	paramCount := int(container.TypeArgc)
	for i := 0; i < paramCount; i++ {
		paramName := "T"
		if i > 0 {
			paramName = fmt.Sprintf("T%d", i+1)
		}

		// Try to get actual parameter name from metadata
		paramIdx := int(container.GenericParameterStart) + i
		if paramIdx >= 0 && paramIdx < len(g.meta.GenericParameters) {
			param := g.meta.GenericParameters[paramIdx]
			if param != nil {
				actualName := g.meta.GetString(int32(param.NameIndex))
				if actualName != "" {
					paramName = actualName
				}
			}
		}

		sb.WriteString(fmt.Sprintf("\tIl2CppClass* _%d_%s;\n", i, paramName))
	}

	sb.WriteString("};\n")
}

// generateGenericInstStructs generates struct definitions for all generic instantiations
func (g *StructGenerator) generateGenericInstStructs(sb *strings.Builder) {
	if len(g.genericInstNames) == 0 {
		return
	}

	sb.WriteString("\n// Generic instantiation structs\n")

	// Forward declarations for generic instantiation types
	var sortedNames []string
	for _, name := range g.genericInstNames {
		if name != "" {
			sortedNames = append(sortedNames, name)
		}
	}
	sort.Strings(sortedNames)

	// Remove duplicates
	seen := make(map[string]bool)
	for _, name := range sortedNames {
		if seen[name] {
			continue
		}
		seen[name] = true

		sb.WriteString(fmt.Sprintf("struct %s_o;\n", name))
		sb.WriteString(fmt.Sprintf("struct %s_Fields;\n", name))
		sb.WriteString(fmt.Sprintf("struct %s_c;\n", name))
	}
	sb.WriteString("\n")

	// Generate the struct definitions
	// For generic instantiations, we generate similar structures to regular types
	// but with the instantiated type name
	seen = make(map[string]bool)
	for typeIdx, name := range g.genericInstNames {
		if name == "" || seen[name] {
			continue
		}
		seen[name] = true

		t := g.types[typeIdx]
		if t == nil || g.staticAnalyzer == nil {
			continue
		}

		g.generateGenericInstStruct(sb, name, t)
	}
}

// generateGenericInstStruct generates struct definitions for a single generic instantiation
func (g *StructGenerator) generateGenericInstStruct(sb *strings.Builder, name string, t *binary.Il2CppType) {
	if t == nil || t.Type != binary.IL2CPP_TYPE_GENERICINST || g.staticAnalyzer == nil {
		return
	}

	gcPtr := t.Data
	if gcPtr == 0 {
		return
	}

	gc, err := g.staticAnalyzer.ReadGenericClass(gcPtr)
	if err != nil {
		return
	}

	// Get the base type definition to copy its fields
	var baseTypeIdx int = -1
	if g.version < 27 {
		baseTypeIdx = int(gc.TypeDefinitionIndex)
	} else if gc.Type != 0 {
		baseType, err := g.staticAnalyzer.GetIl2CppType(gc.Type)
		if err == nil && baseType != nil {
			if baseType.Type == binary.IL2CPP_TYPE_CLASS || baseType.Type == binary.IL2CPP_TYPE_VALUETYPE {
				baseTypeIdx = int(baseType.Data)
			}
		}
	}

	if baseTypeIdx < 0 || baseTypeIdx >= len(g.meta.TypeDefinitions) {
		return
	}

	typeDef := g.meta.TypeDefinitions[baseTypeIdx]
	if typeDef == nil {
		return
	}

	isValueType := (typeDef.BitField & 0x1) != 0

	// Generate _Fields struct (same as base type for now)
	sb.WriteString(fmt.Sprintf("// Generic instantiation: %s\n", name))
	sb.WriteString(fmt.Sprintf("struct %s_Fields {\n", name))

	// Copy fields from base type definition
	if typeDef.FieldCount > 0 && typeDef.FieldStart >= 0 {
		usedNames := make(map[string]int)
		fieldEnd := typeDef.FieldStart + int32(typeDef.FieldCount)
		for fieldIdx := typeDef.FieldStart; fieldIdx < fieldEnd; fieldIdx++ {
			if fieldIdx < 0 || int(fieldIdx) >= len(g.meta.FieldDefinitions) {
				continue
			}
			field := g.meta.FieldDefinitions[fieldIdx]
			if field == nil {
				continue
			}
			fieldName := fixName(g.meta.GetFieldName(int(fieldIdx)))
			fieldType := g.parseTypeIndex(field.TypeIndex)

			// Handle duplicate names
			baseName := fieldName
			if count, exists := usedNames[baseName]; exists {
				fieldName = fmt.Sprintf("%s_%d", baseName, count)
				usedNames[baseName] = count + 1
			} else {
				usedNames[baseName] = 1
			}

			// Check if field is static
			isStatic := false
			if field.TypeIndex >= 0 && int(field.TypeIndex) < len(g.types) && g.types[field.TypeIndex] != nil {
				isStatic = (g.types[field.TypeIndex].Attrs & 0x0010) != 0
			}

			if !isStatic {
				sb.WriteString(fmt.Sprintf("    %s %s;\n", fieldType, fieldName))
			}
		}
	} else if typeDef.ParentIndex < 0 {
		sb.WriteString("    uint8_t __dummy; // empty struct placeholder\n")
	}

	sb.WriteString("};\n")

	// Generate _c struct
	vtableCount := int(typeDef.VtableCount)
	if vtableCount == 0 {
		vtableCount = 4
	}
	if vtableCount > 255 {
		vtableCount = 255
	}

	sb.WriteString(fmt.Sprintf("struct %s_c {\n", name))
	sb.WriteString("    struct Il2CppClass_1 _1;\n")
	sb.WriteString("    void* static_fields;\n")
	sb.WriteString("    union Il2CppRGCTXData* rgctx_data;\n")
	sb.WriteString("    struct Il2CppClass_2 _2;\n")
	sb.WriteString(fmt.Sprintf("    struct VirtualInvokeData vtable[%d];\n", vtableCount))
	sb.WriteString("};\n")

	// Generate _o struct
	sb.WriteString(fmt.Sprintf("struct %s_o {\n", name))
	if isValueType {
		sb.WriteString(fmt.Sprintf("    struct %s_Fields fields;\n", name))
	} else {
		sb.WriteString(fmt.Sprintf("    struct %s_c* klass;\n", name))
		sb.WriteString("    void* monitor;\n")
		sb.WriteString(fmt.Sprintf("    struct %s_Fields fields;\n", name))
	}
	sb.WriteString("};\n\n")
}

// fixName fixes invalid C identifiers
func fixName(name string) string {
	if name == "" {
		return "_empty"
	}

	// Replace invalid characters
	name = strings.ReplaceAll(name, ".", "_")
	name = strings.ReplaceAll(name, "<", "_")
	name = strings.ReplaceAll(name, ">", "_")
	name = strings.ReplaceAll(name, ",", "_")
	name = strings.ReplaceAll(name, " ", "_")
	name = strings.ReplaceAll(name, "-", "_")
	name = strings.ReplaceAll(name, "`", "_")
	name = strings.ReplaceAll(name, "[", "_")
	name = strings.ReplaceAll(name, "]", "_")
	name = strings.ReplaceAll(name, "(", "_")
	name = strings.ReplaceAll(name, ")", "_")
	name = strings.ReplaceAll(name, "/", "_")
	name = strings.ReplaceAll(name, ":", "_")
	name = strings.ReplaceAll(name, "$", "_")
	name = strings.ReplaceAll(name, "@", "_")
	name = strings.ReplaceAll(name, "=", "_")
	name = strings.ReplaceAll(name, "+", "_")

	// Remove consecutive underscores
	re := regexp.MustCompile(`_+`)
	name = re.ReplaceAllString(name, "_")

	// Trim leading/trailing underscores
	name = strings.Trim(name, "_")

	// Ensure it doesn't start with a digit
	if len(name) > 0 && name[0] >= '0' && name[0] <= '9' {
		name = "_" + name
	}

	// Check for reserved keywords
	if cKeywords[name] {
		name = "_" + name
	}

	if name == "" {
		name = "_unnamed"
	}

	return name
}

// GenerateScriptMethods generates method declarations with signatures
func (g *StructGenerator) GenerateScriptMethods() string {
	var sb strings.Builder

	sb.WriteString("// Method declarations\n")
	sb.WriteString("#pragma once\n\n")
	sb.WriteString("#include \"il2cpp.h\"\n\n")

	// Generate method declarations for each type
	for typeIdx, typeDef := range g.meta.TypeDefinitions {
		structName := g.structNameDic[typeIdx]
		if structName == "" {
			continue
		}

		methodEnd := typeDef.MethodStart + int32(typeDef.MethodCount)
		for methodIdx := typeDef.MethodStart; methodIdx < methodEnd; methodIdx++ {
			if int(methodIdx) >= len(g.meta.MethodDefinitions) {
				continue
			}
			methodDef := g.meta.MethodDefinitions[methodIdx]
			methodName := g.meta.GetMethodName(int(methodIdx))

			// Get return type
			returnType := g.parseTypeIndex(methodDef.ReturnTypeIndex)
			if methodDef.ReturnTypeIndex >= 0 && int(methodDef.ReturnTypeIndex) < len(g.types) {
				t := g.types[methodDef.ReturnTypeIndex]
				if t != nil && t.Byref {
					returnType += "*"
				}
			}

			// Build parameter list
			var params []string

			// Add 'this' parameter for instance methods
			isStatic := (methodDef.Flags & 0x10) != 0 // METHOD_ATTRIBUTE_STATIC
			if !isStatic {
				thisType := g.parseTypeIndex(typeDef.ByvalTypeIndex)
				params = append(params, thisType+" __this")
			}

			// Add method parameters
			paramEnd := methodDef.ParameterStart + int32(methodDef.ParameterCount)
			for paramIdx := methodDef.ParameterStart; paramIdx < paramEnd; paramIdx++ {
				if int(paramIdx) >= len(g.meta.ParameterDefinitions) {
					continue
				}
				paramDef := g.meta.ParameterDefinitions[paramIdx]
				paramName := g.meta.GetParameterName(int(paramIdx))
				paramType := g.parseTypeIndex(paramDef.TypeIndex)

				if paramDef.TypeIndex >= 0 && int(paramDef.TypeIndex) < len(g.types) {
					t := g.types[paramDef.TypeIndex]
					if t != nil && t.Byref {
						paramType += "*"
					}
				}

				params = append(params, paramType+" "+fixName(paramName))
			}

			// Add MethodInfo parameter
			params = append(params, "const MethodInfo* method")

			// Generate declaration
			fullMethodName := structName + "$$" + methodName
			sb.WriteString(fmt.Sprintf("%s %s(%s);\n",
				returnType,
				fixName(fullMethodName),
				strings.Join(params, ", ")))
		}
	}

	return sb.String()
}
